name: neofetch-desktop
base: core24
version: git
summary: Neofetch Desktop
description: |
  Shows Linux System Information with Distribution Logo
icon: data/neofetch-desktop.png
grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy/libpxbackend-1.0.so:
    symlink: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy/libpxbackend-1.0.so

parts:
  neofetch:
    plugin: make
    source: https://github.com/hykilpikonna/hyfetch.git
    source-tag: '1.4.10'
    stage-packages:
      - bind9-dnsutils
      - pciutils
    prime:
      - -usr/lib/*/libisccc*.so

  vte:
    source: https://gitlab.gnome.org/GNOME/vte.git
    source-tag: '0.70.5'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Dgir=false
      - -Da11y=false
      - -Dicu=false
      - -Ddocs=false
      - -Dglade=false
      - -Dgnutls=true
      - -Dfribidi=false
      - -Dgtk3=false
      - -Dgtk4=true
      - -D_systemd=false
      - -Dvapi=false
    override-pull: |
      craftctl default
      sed -i 's#error=format#format#' meson.build
    prime:
      - usr/lib/*/libvte*gtk4.so.*
        
  neofetch-desktop:
    after: [ vte ]
    plugin: meson
    source: .
    meson-parameters:
      - --prefix=/usr
    prime:
      - usr/bin/neofetch-desktop
      - usr/share/applications/neofetch-desktop.desktop
      - usr/share/icons

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [neofetch, neofetch-desktop]
    plugin: nil
    build-snaps: [core24, gtk-common-themes, gnome-46-2404]
    override-prime: |
      set -eux
      for snap in "core24" "gtk-common-themes" "gnome-46-2404"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done

apps:
  neofetch-desktop:
    extensions: [ gnome ]
    command: usr/bin/neofetch-desktop
    desktop: usr/share/applications/neofetch-desktop.desktop
    plugs:
      - hardware-observe
      - system-observe
      - network
